const mongoose = require("mongoose");

const foodSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, "Food name is required"],
    trim: true,
    minlength: [3, "Food name must be at least 3 characters"],
    maxlength: [100, "Food name must not exceed 100 characters"],
  },
  video: {
    type: String,
    required: [true, "Video URL is required"],
  },
  description: {
    type: String,
    required: [true, "Description is required"],
    minlength: [10, "Description must be at least 10 characters"],
    maxlength: [500, "Description must not exceed 500 characters"],
  },
  price: {
    type: Number,
    required: [true, "Price is required"],
    min: [0, "Price must be greater than 0"],
    max: [10000, "Price seems unrealistic, please check"],
  },
  foodItem: {
    type: String,
    required: [true, "Food item category is required"],
    enum: {
      values: [
        "Pizza",
        "Burger",
        "Pasta",
        "Biryani",
        "Sushi",
        "Tacos",
        "Curry",
        "Steak",
        "Chicken",
        "Fish",
        "Salad",
        "Sandwich",
        "Noodles",
        "Rice",
        "Bread",
        "Soup",
        "Dosa",
        "Samosa",
        "Kabab",
        "Falafel",
        "Ramen",
        "BBQ",
        "Grilled",
        "Baked",
        "Fried",
        "Smoothie",
        "Cake",
        "Dessert",
        "Coffee",
        "Tea",
        "Juice",
        "Wrap",
        "Bowl",
        "Platter",
        "Kebab",
        "Shawarma",
        "Dim Sum",
        "Dumpling",
        "Momos",
        "Thali",
        "Paneer",
        "Seafood",
      ],
      message: "{VALUE} is not a valid food item",
    },
  },
  foodPartener: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "foodpartener",
    required: [true, "Food partner is required"],
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

const foodModel = mongoose.model("food", foodSchema);

module.exports = foodModel;
